### ISSUE TITLE
Implement Promo Codes and Tracking

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#197]
@joshdanielson commented on [Sat Feb 06 2016](https://github.com/joshdanielson/loconomics-internal/issues/891)

# Overview:

Implement promo code tracking of referrals.  Invite includes incentive (e.g. six months free, annual fee waived, etc.)
## Related Issues:
#385 - Examples of other company's programs
#739 - Add Unique Referral Code to each user upon Sign up
#619 - Refer a provider (from a customer)
## Mockups (if any):

Mockups of the creative.
## PSD/AI files (if any):

file names of photoshop/illustrator files related to the issue
## Pages (if any):

URL of the pages affected
## To-dos:

Clear instructions of what needs to be completed 

marketing strategy table
reach, relationship
- [ ] Create a marketingcampaigns database table with the following fields:
  - campaignID (auto-generated)
  - campaignName
  - campaignDescription
  - campaignFlightDateIn
  - campaignFlightDateOut
  - campaignLead
  - flightStatusID
- [ ] Create a channel type table with the following fields:
  - sem, seo, events, PR, paid social, earned social, email, direct mail, collateral, 
- [ ] Create a marketingflightstatus table with the following fields: 
- flightStatusID
- flightStatusName
- flightStatusDescription
- active
- status: scheduled, inflight, flown, cancelled
- [ ] Create marketingpromotions database table with the following fields:
  - promotionID (auto-generated)
  - campaignID
  - localeID
  - promotionName (string 100 characters)
  - promotionFlightDateIn
  - promotionFlightDateOut
  - promotionCodePrimary
  - promotionCodeSecondary
  ## \- promotionCodeTertiary
- [ ] Task 2
- [ ] Task 3

**_Testing Scenarios (if any):**_  
Stories of how a user will interact with the marketing in regards to the issue with clear success criteria
- [ ] Test 1
- [ ] Test 2
- [ ] Test 3
