### ISSUE TITLE
Website-7: Further work

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#203]
@IagoSRL commented on [Tue Feb 23 2016](https://github.com/joshdanielson/loconomics-internal/issues/921)

The series of back-end releases _Release-7.x_ needed for the App-v1 required to update the website with all-new content and design using the shared App code. Responsive design, REST API, new tools and reorganization, comes too with big bundle files for client-side rendering (webapp) and zero server-size rendering: the server just returns a big static html file for all website pages.

Initial preparation was performed as of #842 (_it just works_), but further work is required, mainly for **size**, **performance**, **SEO/search-engine friendly**
### Tasks

More can come in further comments/updates, or split into several issues.
- [ ] Light home page, able to work without javascript:
  - [ ] It means: when requesting the home page, server must return a specific, home-only, html and css files (right now it downloads bundle files with all the content for all html, css, js --too big).
  - [ ] That html must show the content right away (current webapp/app set-up hides all html after the javascript is loaded and initialized, letting the js-shell to manage visualization of content; that does not work well for a fast web experience, while is needed for a full webapp/SPA).
  - [ ] With lazy loading of javascript, to enable the full webapp and background/on-demand download of the rest of content and features.
  - [ ] Initial html must be compatible in structure with the full html bundle, and the (lazy loaded) javascript must upgrade it to behave as SPA with the js-shell managing the content.
- [ ] SEO: server-side rendering needed for search results. #833 needed before attempt this, since the html code created there need to be copied and adapted as a server-side page.
- [ ] Use URLs without the _hash-bang_, using browsers native HistoryAPI at the js-shell rather than current 'hashbangHistory' (this last required for App, and browsers without/broken HistoryAPI support). Along with specific server-side URL rewriting for the existent activities rather to behave like a 'catch-all' like now, then returning a server not-found on non existent activities.
  - [ ] As of 03/01/2016, several fixes were added to make the Webapp Shell detects standard URLs, detect and manage properly the baseURL, while still using the Hashbang library; the transition from standard URL to hashbang URL is not completely clean thought, requiring extra work: the baseUrl path is being used in the hashbang even if must not (clicking a menu link for example) and the URL path is not rewritten when the rewriting logic starts setting hashbangs for navigation.
- [ ] Optimize js, css, html
  - [ ] replace heavy js components by light versions or custom code. Try to upgrade browserify since latest versions include more browser optimized utils (rather than wrapped node utils), and more optimizations.
  - [ ] remove unused CSS styles, look for some post-css tool to auto-remove unused selectors.
  - [ ] simplify html, reduce dupes, and integrate a tool to minify the static html.
- [ ] split current bundles in smaller parts (maybe 2-5), just loading only the needed for a set of activities. How much it depends on how large they are (after optimizations) and interrelations of the code (activities, components, utils).

---

@IagoSRL commented on [Mon Feb 29 2016](https://github.com/joshdanielson/loconomics-internal/issues/921#issuecomment-190384411)

Just to document here: A Grunt task to minify html was added (it's at _master_), with **conservative** settings but still being able to remove comments while keeping the functional Knockout comments.
Still further work may be needed on html.

---

@IagoSRL commented on [Fri Mar 04 2016](https://github.com/joshdanielson/loconomics-internal/issues/921#issuecomment-192386882)

As a general change, too for the App code: 
- [ ] Disable static images from loading on start-up, if the activity they belongs is not visible.

Comments on this:
- It happens now with Home/search page icons, download-app icons (they are remote, causing to a remote load to happens even if never needed).
- A possible solution is to remove the 'src' with a 'data-src' and switch them on first initialization, but may be problematic for code reuse on website (to enable first-time paint without javascript).
- Alternative, bigger but maybe better: move all activities html to components/custom-elements/templates, make the Activity init or Shell router to generate a new instance of the activity using the template. **Not only unneeded images loading** fixes with this, but maybe the amount of initial memory used drops, _maybe_ the start-up is faster, needs to be measured and check side effects.
