### ISSUE TITLE
Adapt Review System for App

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#30]
## Prototypes (in branch):

/userReview (need to add /@bookingID/@userID eventually)
## Database changes:
- [ ] Remove positionratings (check code to see if used):
- [ ] Add to positions:
  - SuppressReviewOfClient (make it impossible to review client)
  - SuppressReviewOfServiceProfessional (make it impossible to review service professional)
  - RequestToReview (determines whether we prompt the user to review outside of the booking)
## To-dos:

Clear instructions of what needs to be completed 
- [ ] Review what's currently implemented:
  - web/App_Code/LCRest/PublicUserRating.cs (follow up through api to app/source/js/models/PublicUserRating.js)
  - web/App_Code/LCRest/PublicUserReview.cs (follow up through api to app/source/js/models/PublicUserReview.js)
- [ ] Revise PublicUserRating to include:
  - answer1
  - answer2
  - answer1Comment
  - answer2Comment
- [ ] Review prototype in issue874 branch at /userReview to see what the review will look like
  - change this.isClient to false and this.isServiceProfessional to true in .js file to see client review example
- [ ] Create backend for API in UserReview that includes:
  - GET call to pull from JobTitleReviewRules to know if booking should allow for /userReview 
  - POST call to put form data into UserReviews
  - Update function to update UserReviewScores after each review
  - Most code (not all needed) can be found here in [this dropbox folder](https://www.dropbox.com/sh/f8qbc0323b0p1cf/AAC0BJytmyxtC2YO8wOVSzDVa?dl=0).
  - POST to Deemly (if user has Deemly account)
- [ ] Create responsive page with new design for review form:
  - app.html#!/reviewUser/@(BookingID)/@(UserID)
  - include client sign up if new user with agree to TOS on second step pulling user data from service professional? Ask them to verify their name, email, and ask to create password.
- [ ] Create rules for reviews in positions table 
  - suppress review reminders for certain positions
  - suppress the ability to review clients for certain positions
  - suppress the ability to review service professionals for certain positions
- [ ] Create general rules for reviews in UserReview.cs:
  - Ability to review for 14 days after service endDate
  - Suppress review for 14 days or both review
  - Suppress reviews according to positions table
- [ ] Create Rules for sending communications:
  - If user has reviewed the other user for job title in last six months, do not send reminders
  - If user hasn't reviewed the other user for job title in last six months, send reminders only if it's been 30 days since last booking
- [ ] Create communication to Service Professional that a review has been completed with client comments after each review or 14 days
- [ ] Create communication to Client that a review has been completed with service professional comments after each review or 14 days
- [ ] Include NPS survey after last step but don't require user to do it (POST review results first)
- [ ] Create "Reviews" area of dashboard:
  - Reviews of me
  - My reviews of others
- [ ] Create ability to respond to a review 
  - use Answer2 with a "Do you agree with this review?" Yes/No
  - use Answer2Comment for the public review response
