### ISSUE TITLE
Add Detailed Validation to Password Creation Form

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#318]
## Child Story
As a Loconomics User, I want to be able to easily **meet the requirements** of creating a *password* and be told *what I'm missing* and *when I'm done*.

### Test Cases
1) Make sure the user knows if they have entered 8 characters
2) Make sure the user knows if they've entered a capital letter
3) Make sure the user knows if they've entered a lowercase letter
4) Make sure the user knows if they've entered a number
5) Make sure the user knows if they've entered a symbol
6) Make sure the user knows if they've met the requirements of a strong password (8 characters and three of the four other requirements)
7) Make sure the user is reminded in the placeholder for password to "Make it tricky, yet memorable".
8) Make sure it's on the password reset form

### Examples
![pw](https://cloud.githubusercontent.com/assets/1202838/24057806/ebdbf134-0b05-11e7-9e4d-8bfb702333d9.png)
![pw2](https://cloud.githubusercontent.com/assets/1202838/24057810/f2a106b2-0b05-11e7-82c4-d5f256441662.png)

## To-do
- review existing validation in user sign-up for other fields
- [ ] Create .js validation for each of the test cases above
- [ ] Create css/html to display validation like the examples
- [ ] Add the placeholder "Make it tricky, yet memorable"

**Comment by IagoSRL** [comment]
2

**Comment by situatedbit** [comment]
estimate: 3

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
Here's what I'm playing with:

![password-validation](https://cloud.githubusercontent.com/assets/6644016/24720823/366feb28-19f3-11e7-9983-247e1c3a881b.png)

**Comment by situatedbit** [comment]
@IagoSRL Josh and I discussed removing the second password field in the reset password form. This would require modifying the API as well. Since we don't require a second password during sign-up, I don't think we should require a second password during password reset. What do you think?

**Comment by IagoSRL** [comment]
@situatedbit It's OK to remove the repeat-password field from API too.

I suppose the general idea now is that, if you typed wrongly your password, you ever can ask to reset it again.

**Comment by joshdanielson** [comment]
@situatedbit @kyraharrington and I both tested. Looks great...nice work! Good password validation!

**Comment by IagoSRL** [comment]
I think this is already well tested by all, so I'm closing.
