### ISSUE TITLE
Implement Multi-session Services

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#44]
## Epic Story 3
As [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md), I'd like clients to be able to book repeat services with me so I can see them more often and generate more income.

Epic Story 3: Child Story A | Target Persona(s) | Investable 
------------ | ------------- | ------------- 
I want clients who have purchased multi-session services to see and book their remaining sessions so I don't have to keep track of them.| [Felicity the Fitness Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Felicity%20the%20Fitness%20Professional.md) | Yes 
**Test Cases** | **GitHub Issue** | **Complete** 
A1) Make sure the client can see the remaining sessions they purchased. | [44](https://github.com/loconomics/loconomics/issues/44) | -  
A2) Make sure the service professional can see the remaining sessions a client has purchased. | [44](https://github.com/loconomics/loconomics/issues/44) | - 
A3) Make sure the client book each of the remaining sessions. | [44](https://github.com/loconomics/loconomics/issues/44) | - 
A4) Make sure the service professional can book for the client the remaining sessions. | [44](https://github.com/loconomics/loconomics/issues/44) | - 
A5) Make sure there is no payment is requested since it's already paid for. | [44](https://github.com/loconomics/loconomics/issues/44) | - 

1. Client or freelancer makes a booking for a multi-session package and schedules first session only
2. Client pays (through marketplace or freelancer) 
3. ProviderPackage copied and NumberOfSessions set to original minus 1, ClientUserID and SpecialPricingTypeID=1, and BasedONProviderPackageID=XX)
4. MultiSession flag = 1 
5. ParentBookingID= original booking ID (except for 1st booking)
6. Client and freelancer see any package bookings with remaining sessions in the "TO BE SCHEDULED" part of the dashboard and my providers/clients sections. (using a query of any bookings with SpecialPricingTypeID=1 and Active=1)
7. When client or freelancer goes to book a remaining session or any new booking, the remaining sessions show up in SELECT SERVICES with $0 as the price and X left, 120 minutes each. The client or freelancer can select this (pre-selected if they click from "TO BE SCHEDULED") and any additional services they want. If client booking, they pay for additional services.
8. NumberofSessions deducted by 1
9. When numberofSessions=0, set Active=0
## Mockups (if any):

Mockups of the front-end design or diagrams of processes
## Database tables (if any):

New Fields to ProviderPackage table:
ClientUserID
BasedOnProviderPackageID
SpecialPricingTypeID (0=normal, 1=SessionsRemaining, 2=VIP)
## Pages (if any):

URL of the pages affected
## To-dos:

Clear instructions of what needs to be completed 
- [ ] Update current pricing listing (that goes to any user) to not include special pricings (add SpecialPricingTypeID=0 to the query).
- [ ] Add rule to freelancer edit pricing API so does not allows to create/modify/delete a SessionsRemaining pricingID (VIP pricing may need its own rules, to manage on its own issue). Creation of this kind of pricing is done only by internal API from bookings.
- [ ] Logic to mix freelancer pricings and related customer special pricings, so special ones replace any standard pricing that equals the BasedOnID.
- [ ] New API to let a client read the special pricings it has with a freelancer, with difference from SessionsRemaining and VIP. Double check if has sense to integrate the listing of SessionsRemaining with the general API that reads pricings from a provider.
