### ISSUE TITLE
Create a client account from a booking confirmation

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#51]
# Overview:

Clients who were scheduled by a service professional should be able to sign up easily by clicking on any link from their booking confirmation (View booking, change/cancel, etc.).
## Related Issues:
#900
## To-dos:

Clear instructions of what needs to be completed 
Steps:
- Service Professional makes a booking for a client who doesn't have an account
- Client receives booking-related e-mail communications
- If client wants to view the booking or make a change, then (**this is my proposal**):
- [ ] Any link they click on on the booking communication  (View booking, change, cancel) for clients where accountNeedsConfirmation is TRUE will land them on the signup/client form with these changes:
  - [ ] "Already have an account? Login" is hidden
  - [ ] "Sign up for free" is changed to "Create your free account"
  - [ ] e-mail address is entered (and not able to be edited)
  - [ ] Client then enters their name, password and clicks "Create account"
