### ISSUE TITLE
Remove user type selection from generic sign-up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#588]
## User Stories
As a potential provider, I want to add a listing on loconomics after I sign up so I have the opportunity to first evaluate whether loconomics is right for me.

As a potential client who simply wants to book services, I want to sign up without having to make one extra decision about whether I'm a provider or client.

## Tasks
- [x] Default users that sign up from home page (not landing) to isClient
- [x] Remove the sign up menu dropdown from the wide layout
- [x] Remove the distinct sign up links in the menu from the narrow layout

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
3
