### ISSUE TITLE
Add weekly schedule to listing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#590]
## User Story
As a client, I want to see when a service professional generally offers their services.

## Tasks
- [x] Add weeklySchedule data to listing.js
- [x] Show text version of weekly schedule on listing (use abbr tag for days of week)
- [x] Included edit button to service professional

**Comment by joshdanielson** [comment]
This is completed on the is580 branch.
