### ISSUE TITLE
Revise OnboardingSuccess.html with Next Steps

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#591]
## User Story
As a service professional in onboarding, after entering my public contact info, uploading my profile photo (or skipping), and job title, I want to know what's next.

## Task
- [x] convert to modal as overlay to listingEditor.html for professionals and home.html for clients (use announcement as a template)
- [x] Explain next steps to service professional
  - Title: What's next?
  - Next we will show you your listing so you can edit and enhance it
  - When you're ready, you can make your listing public to potential clients and other professionals
- [x] Explain next steps to client 
  - Title: Thank you!
   - Find and schedule local services

**Comment by joshdanielson** [comment]
3

**Comment by RialtoBeach** [comment]
3

**Comment by IagoSRL** [comment]
3

**Comment by ardanak** [comment]
3

**Comment by IagoSRL** [comment]
Done, pushed to branch is584

**Comment by joshdanielson** [comment]
@IagoSRL, looks great! Closing.
