### ISSUE TITLE
Separate AboutMe Activities

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#593]
## User Story
As Loconomics handling bookings for new service professionals, we need to know a minimum amount of information to facilitate a client booking.

## Tasks
- [x] Reduce AboutMe to only the following fields and rename it publicContactInfo:
   - First Name
   - Last Name
   - Phone number
   - Business Name
- [x] New activity for publicBio
- [x] New activity for publicProfilePicture
- [Move Your address (for our records) to /paymentAccount (#685)
- serviceProfessionalCustomURL moved to #698
- [x] New activity for serviceProfessionalCustomURL (premium feature) in Profile menu
- [x] New activity /serviceProfessionalBusinessInfo (premium feature) from listingEditor with businessName and  serviceProfessionalBusinessWebsiteURL
- [x] Profile menu order:
   - publicContactInfo
   - publicProfilePicture
   - publicBio
   - userBirthDay

**Comment by IagoSRL** [comment]
3

**Comment by RialtoBeach** [comment]
3

**Comment by ardanak** [comment]
3

**Comment by joshdanielson** [comment]
3

**Comment by joshdanielson** [comment]
This was completed as part of #580.
