### ISSUE TITLE
Create Add/Edit Buttons for each Listing Activity

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#599]
## User Story
As a service professional, I want to edit details directly from my listing.

## Task
- [x] Create buttons for each activity in listing
- [x] Create two states for buttons:
  - Add Activity (if hasActivityName is false)
  - Edit Activity (if hasActivityName is true)
- [x] href should be equal to activtyName.html and include backlink "Back to JobTitle Listing"

**Comment by joshdanielson** [comment]
Completed as part of #580.
