### ISSUE TITLE
Create & Apply "Upgrade" label and explanation

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#616]
## User Story
Create a label/button to make it clear to the service professional what features are premium and explain the value proposition and why they should upgrade.

## Tasks
- [ ] Create label/button that links to /upgrade activity
- [ ] Include a value proposition
- [ ] Preselect the plan that includes the feature the user clicked on
