### ISSUE TITLE
Add Newsletter signup component

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#671]
### User story
As a new visitor to Loconomics.com, I'd like to sign up for a newsletter so I can stay informed on what Loconomics is up to.

#### Test cases
- User is able to easily find where to sign up
- User can enter their email address
- User receives real-time confirmation they're signed up for the newsletter
- User is flagged in our database as a newsletter subscriber

#### To-do
- [x] Create lead-generation-newsletter index.js and template.html component files
- [x] Complete lead-generation-newsletter template.html 
- [ ] Complete lead-generation-newsletter index.js visible functions:
  - submitted (has form been submitted yet?)
  - searchFailure (is the module being shown when there are no search results?)
  - searchCity (captures the city being searched)
- [ ] Create user from lead-generation-newsletter submitted data with following fields:
  - userID: 0,
  - email: '',
  - isServiceProfessional: (true if checkbox checked, false if not checked),
  - isClient: true,
  - accountStatusID: (I'm wondering if we set this to -1 for any users that have not created a password? or something like that),
  - createdDate: null,
  - updatedDate: null
- [ ] Ensure users.LoconomicsMarketingCampaigns is set to 1 (I think this probably happens already)

**Comment by IagoSRL** [comment]
Thinking in save at the [users].[marketingSource] column the value '&lead-generation=newsletter' (appended to whatever comes. Is that enough or we should have columns to tag that comes from newsletter, or referral? (the [LoconomicsMarketingCampaigns] would be set as 1, but that's too the default for any other user).

**Comment by joshdanielson** [comment]
That should be sufficient as long as we can reference the value in creating communications. We’ll start with emailing them manually and eventually move to automate so would use it then.

**Comment by joshdanielson** [comment]
@IagoSRL this looks good!

**Comment by IagoSRL** [comment]
I pushed the implementation of this REST API to *dev*. Can be tested with TestREST (is the last example)

**Comment by joshdanielson** [comment]
@IagoSRL just tested this and got an error. However, I haven't tested anything on here in a long time so maybe I'm doing something wrong:
![screen shot 2017-11-16 at 12 13 29 pm](https://user-images.githubusercontent.com/1202838/32913611-a8093174-cac7-11e7-9a07-5805d65c3e44.png)

**Comment by IagoSRL** [comment]
I updated the REST API to only allow anonymous users, same as commented for #673.
The UI should prevent from display the component to logged users, but in case of any mistake or different API usage the error returned is `You are already logged in! Review your account preferences to enable the newsletter.`.

**Comment by IagoSRL** [comment]
Fixed the error you commented @joshdanielson

**Comment by joshdanielson** [comment]
@iagosrl for logged in users how about just setting the marketing promotions flag to 1 if they enter their email? And if it’s already 1, just leave pretend it wasn’t :) I think it’s way better than an error or pop-up.

**Comment by IagoSRL** [comment]
Implemented ViewModel for the 'newsletter' component and pushed, with documentation. It's simple so must be easy to connect, but feel free to request me to do it once to put the correct html in the component template file

**Comment by IagoSRL** [comment]
@joshdanielson I pushed to the branch changes in the binding for the newsletter component, working. Please review and adjust if you want some details, I think specially the state after submit successfully can get better (now the bottom message changes and form elements kept disabled, but maybe the form should hide and keep just the message? an informational modal can be showed too, as happened with errors when happens --try an existent e-mail).
Remember that to use a component, it's must be `require`d from Javascript (on this case, at the home.js to be used in the activity).
I replaced the html at the searchJobTitle by an instance of the component.

Not sure if related with you latest changes at `home.html` and styles, but I can some styles bugs like h2 headers wrongly aligned, some vertical white lines at search categories cards. Too, the lead generation components don't render well at different sizes, maybe should I review and re-do the styling for this? (let me know)

**Comment by joshdanielson** [comment]
@IagoSRL I fixed the css and updated the isDone html for the newsletter component...I "think" it's all good! I also tested it fully on both home and search results and all working well.

I didn't get to the weird header and slight white line you mentioned (I noticed too).

Speak tomorrow!

**Comment by IagoSRL** [comment]
I pushed small changes with an additional message and link to privacy settings when the user is already logged. @joshdanielson Update the language for that (is at the top in the template).
