### ISSUE TITLE
Add professional referral component

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#673]
### User story
As a new visitor to Loconomics.com, I'd like to help Loconomics grow by introducing Loconomics to any local service professionals I know so they can get listed.
#### Test cases
- User is able to easily find where to refer professionals
- User can enter their information (email, first and last names)
- User can enter the information of the service professional they want to refer (firstName, email, phone)
- User is asked to enter the information of another service professional (loop). They can ignore if they don't know any more.
- User receives real-time confirmation they've referred the service professional
- User referring is created as a new User in our database
- User referring is flagged in our database as a newsletter subscriber
- User referred (service professional) is created as a new User in our database and mapped to referrer

#### To-do
- [x] Create lead-generation-refer index.js, template.html. and template.styl component files
- [x] Complete lead-generation-refer template.html 
- [ ] Complete template.styl CSS using examples from booking.styl
- [ ] Complete lead-generation-refer index.js visible functions:
  - submitted (has form been submitted yet?)
  - isAtStepOne, isAtStepTwo, isAtStepThree
  - isLoadingStepOne, isLoadingStepTwo, isLoadingStepThree
- [ ] Create user for Referrer from referProfessionalsForm-StepOne submitted data with following fields:
  - userID: 0,
  - email: '',
  - isClient: true,
  - accountStatusID: (I'm wondering if we set this to -1 for any users that have not created a password? or something like that),
  - createdDate: null,
  - updatedDate: null
- [ ] Update Referrer user from referProfessionalsForm-StepTwo submitted data with following fields:
  - firstName: '',
  - lastName: '',
  - updatedDate: dateTime
- [ ] Create user for Referred Professional from referProfessionalsForm-StepThree submitted data with following fields:
  - userID: 0,
  - email: '',
  - firstName: '',
  - isServiceProfessional: true,
  - isClient: true,
  - referredByUserID: referrerUserID,
  - accountStatusID: (I'm wondering if we set this to -1 for any users that have not created a password? or something like that),
  - createdDate: null,
  - updatedDate: null
- [ ] Ensure users.LoconomicsMarketingCampaigns for all users is set to 1 (I think this probably happens already)

**Comment by IagoSRL** [comment]
Proposed REST API design:
# Referral - Step 1

## REST API
POST /lead-generation/referral/subscribe
- email:string
- firstName:string [Optional]
- lastName:string [Optional]

## Restrictions
- Validate email format
- Email does not exists

## Storage
At [userprofile]:
- userID: [auto]
- email: data.email

At [users]:
- userID: userprofile.userID
- isServiceProfessional: false
- isClient: true
- accountStatusID: -1
- loconomicsMarketingCampaigns: true
- firstName: data.firstName
- middleIn: ''
- lastName: data.lastName
- secondLastNme: ''
- marketingSource: context.url.queryString + '&lead-generation=referral'
- preferredLanguageID: context.locale.languageID
- preferredCountryID: context.locale.countryID
- createdDate: DateTime.Now
- updatedDate: DateTime.Now
- active: true

## Result
- userID:int

## Triggers
- Send e-mail "Subscribed to Loconomics newsletter" **?**

# Referral - Step 2

## REST API
POST /lead-generation/referral/refer
- email:string
- firstName:string
- phone:string [Optional]
- referredByUserID:int

## Restrictions
- Validate email format
- Email does not exists

## Storage
At [userprofile]:
- userID: [auto]
- email: data.email

At [users]:
- userID: userprofile.userID
- isServiceProfessional: true
- isClient: true
- accountStatusID: -1
- referredByUserID: data.referredByUserID
- loconomicsMarketingCampaigns: true
- firstName: data.firstName
- middleIn: ''
- lastName: data.lastName
- secondLastNme: ''
- mobilePhone: data.phone
- marketingSource: context.url.queryString + '&lead-generation=referral'
- preferredLanguageID: context.locale.languageID
- preferredCountryID: context.locale.countryID
- createdDate: DateTime.Now
- updatedDate: DateTime.Now
- active: true

## Result
"OK"

## Triggers
- Send e-mail "Thank you! You have referred [service professional.firstName]"

**Comment by IagoSRL** [comment]
Note the question mark around 'sending email Subscribed to Loconomics newsletter' at step 1; worse case of sending that on this design of treat each step as separated API calls, just sent immediately when user clicks the button, is that can get 2 emails (even one for each referred professional). I think that's fine still, but just wanted confirmation.

**Comment by joshdanielson** [comment]
@IagoSRL let's leave out the email triggers for now. What I envision when we automate is we send an email to the referred professional from the client (their first and last name shows in the from field with their email or a generic loconomics one (maybe better), and the client is cc'd on it. The email will be the invitation to join. I think it's a separate issue and we should experiment a bit manually first. THoughts?

**Comment by joshdanielson** [comment]
@IagoSRL in Step 2, can email be optional? I think it's very common for clients to have service professional's phone numbers but not emails or vice versa.

Also, I added a checkbox to the refer module where the user can check "I provide local services" so that if they check that, they should be flagged isServiceProfessional in Step 1.

**Comment by IagoSRL** [comment]
The emails were in the task list of this issue (was an email to the client filling up the form); but OK to left them out (you can cross out the tasks in the first comment and open a new issue).

OK about the checkbox, so is just like in the newsletter component.
OK to optional professional email (it limits the possibility of sending a future email, but I understand the commented use case). The firstName is required all time.
A new question: asking just for professional name can lead to clients to type the full name in one field, or the business name (will we store all at firstName field anyway?)

I set name for client optional (just requiring email), do you want to make it required? (so can be used in a future email to professionals as you commented)

**Comment by joshdanielson** [comment]
@IagoSRL good questions. I guess let's start with required for client first and last name? There's advantages to both, but us referring a service professional from an unknown name doesn't have much use, and we will store their email anyway if they leave, right? 

And for the service professional, you're right, let's put their first and last name but only require their first.

Thanks for thinking these through

**Comment by IagoSRL** [comment]
OK, some doubts:
- *we will store their email anyway if they leave, right?* I don't what you mean with this; in the component form you are required email, first name and last name, right? so if does't validates it doesn't saves...
- wait, is expected that email and name being requested at different steps? So second step should put to an API to update the record?
- *And for the service professional, you're right, let's put their first and last name but only require their first.* OK, remember to put the last name at the component form.

**Comment by joshdanielson** [comment]
- @IagoSRL sorry if that wasn't clear. Yes, they'll be requested at different steps, so yes, the 2nd step would be an update.

- yes, I can add last name to the component form

**Comment by IagoSRL** [comment]
OK! Updated doc for REST API design with latest comments (please double check just in case):

# Referral - Step 1: Subscribe client with email

## REST API
POST /lead-generation/referral/subscribe
- email:string
- isServiceProfessional:boolean

## Restrictions
- All input data is required
- Validate email format
- Email does not exists

## Storage
At [userprofile]:
- userID: [auto]
- email: data.email

At [users]:
- userID: userprofile.userID
- isServiceProfessional: data.isServiceProfessional
- isClient: true
- accountStatusID: -1
- loconomicsMarketingCampaigns: true
- firstName: ''
- middleIn: ''
- lastName: ''
- secondLastName: ''
- marketingSource: context.url.queryString + '&lead-generation=referral'
- preferredLanguageID: context.locale.languageID
- preferredCountryID: context.locale.countryID
- createdDate: DateTime.Now
- updatedDate: DateTime.Now
- active: true

## Result
- userID:int

## Triggers
- Send e-mail "Subscribed to Loconomics newsletter"  *disabled for now, waiting for later template implementation*

# Referral - Step 2: Update client with name

## REST API
PUT /lead-generation/referral/subscribe
- userID:int
- email:string
- firstName:string
- lastName:string

## Restrictions
- All input data is required
- Check that userID and email exists and matches the same user (it prevents from sending random IDs in the request, since this calls are anonymous, and we cannot validate a user session for the subscribed client because is not an active and password enabled account still).

## Storage
Update [users] Where
- userID = data.userID
Set:
- isServiceProfessional: data.isServiceProfessional
- firstName: data.firstName
- lastName: data.lastName
- updatedDate: DateTime.Now

## Result
"OK"

# Referral - Step 3: Refer service professional

## REST API
POST /lead-generation/referral/refer
- email:string [Optional]
- firstName:string
- lastName:string [Optional]
- phone:string [Optional]
- referredByUserID:int
- referredByEmail:string

## Restrictions
- Validate email format
- Email does not exists
- Check that referredByUserID and referredByEmail exists and matches the same user (it prevents from sending random IDs in the request, since this calls are anonymous, and we cannot validate a user session for the subscribed client because is not an active and password enabled account still).

## Storage
At [userprofile]:
- userID: [auto]
- email: data.email or [autogenerated non-email (a value is required and must be unique)]

At [users]:
- userID: userprofile.userID
- isServiceProfessional: true
- isClient: true
- accountStatusID: -1
- referredByUserID: data.referredByUserID
- loconomicsMarketingCampaigns: true
- firstName: data.firstName
- middleIn: ''
- lastName: data.lastName
- secondLastNme: ''
- mobilePhone: data.phone
- marketingSource: context.url.queryString + '&lead-generation=referral'
- preferredLanguageID: context.locale.languageID
- preferredCountryID: context.locale.countryID
- createdDate: DateTime.Now
- updatedDate: DateTime.Now
- active: true

## Result
"OK"

## Triggers
- Send e-mail "Thank you! You have referred [service professional.firstName]" *disabled for now until email templates are implemented*

**Comment by joshdanielson** [comment]
@IagoSRL looks good. A couple clarifications/questions:
- when entering the service professional's email or phone...at least one should be required (meaning if they don't enter either, it shouldn't save)
- just thinking out loud, if the email the client enters already exists:
  - if the account statusID is >-1, then they should get a pop-up "You already have an account created, please sign in", then then sign in, and are taken back to step 2 of the component. 
   - the account statusID of the account email they entered is -1 (already exists), can they just be taken to step 2? can we pull their name info or perhaps just re-write it if not? Not sure...what do you think?

- this also brings the question of how we display these components to logged in users. The newsletter component should likely be hidden, but we'd want to show the referral one. 

Sorry so many details still.

**Comment by IagoSRL** [comment]
I thought on the problem with existing email for both anonymous and logged users, and for now I just throw an error. Part of my thoughts was too to move user to other step, return the proper userID or even if checked to be professional but was registered as client before, update the flag for professional and if statusID is valid then should start onboarding and create a bookCode too since is the standard behavior (or the profile will get broken in some way if not done), and... yes, many details, even more thinking on security/privacy problems coming from have a public API that allows to check what emails exists, too if we move to another step we are in some way allowing any user to use another one email..but actually we allow that since it doesn't require email confirmation anyway.
And I stopped my self there, just throwing error asking user to log-in or request a password reset (still we are giving information about existent emails but is a balance between that and allow to continue the process as normally).

**Comment by IagoSRL** [comment]
As you can check, in the updated API doc I added a verification of email and userID for second and third steps almost as minimum guarantee that the same user that started is the one following, and not random request to that steps from anyone. It's a minimum even if I'm not sure if enough to prevent bad usage.

**Comment by IagoSRL** [comment]
About ask for phone or email, OK

About referral component for logged users, I think makes sense. I can update the API to allow a valid logged token (and relate with that user) or the pair of userID and email. In the UI, it should show directly the third step.

**Comment by joshdanielson** [comment]
@IagoSRL all good! this all makes sense to start without going overboard.

**Comment by IagoSRL** [comment]
I updated last comment with the API design to reflect last decisions, and added note in the first comment to denote is a deprecated draft (prevent mistake when reading the issue).

**Comment by IagoSRL** [comment]
@joshdanielson I pushed to *dev* and the branch the fully implemented REST API for this too. You can make some extra test at TestREST.

**Comment by joshdanielson** [comment]
@IagoSRL still getting the same error messages:
![screen shot 2017-11-17 at 10 16 50 am](https://user-images.githubusercontent.com/1202838/32962227-8e4c0158-cb80-11e7-84a0-7b9aed3cf57f.png)
![screen shot 2017-11-17 at 10 16 07 am](https://user-images.githubusercontent.com/1202838/32962228-8e6ef28a-cb80-11e7-94ff-01c42028a1d2.png)

**Comment by IagoSRL** [comment]
Pushed to the branch last change with a data module for the App to connect components with the REST API

**Comment by IagoSRL** [comment]
Reuploaded the file (I thought I did it!)

**Comment by IagoSRL** [comment]
@joshdanielson I just pushed changes implementing ViewModel and binding for the component, please review it.

**Comment by joshdanielson** [comment]
@IagoSRL all working! I'll work a bit on the css touch-ups (making the button larger, etc.
