### ISSUE TITLE
Replace button-click with form-submit event for the main form action

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#692]
### Long Description
At forms we are using click handlers at buttons to trigger actions like 'save', 'create' or anyone that means we are 'submitting' the form. The good practice is to use the form submit event (usability and accessibility recommendation, but not mandatory).

At first it seems trivial to do the change but for some reason is not, we faced problems where the submit event did nothing like in the addressEditor case (see #652, we workaround there by using button-click event).

### Tasks
- [ ] Research why using form-submit didn't worked at addressEditor and solution.
- [ ] Research if same addressEditor problem may happen at other forms.
- [ ] Update all forms using form-submit.
- [ ] Describe this good practice at documentation.
