### ISSUE TITLE
Ability to issue and display badges

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#747]
## User Story
We want to be able to issue badges to students as well as other users so they can display them on their listing and elsewhere.  
### Test Cases
- Loconomics has a Badgr account with Issuer privileges.
- Loconomics can issue a user a badge.
- Loconomics can display a user's badge from elsewhere.
- Users can access Loconomics badges using Badgr.

### To-do
- [x] Make sure we use the Badgr open source standard.  
- [x] Make sure badges are listed on the student's listing. 
- [ ] Make sure the student knows they can list the badges elsewhere. 
- [ ] Make sure we can log into Badgr user OAUTH on behalf of the student.

**Comment by ndarilek** [comment]
The branch now includes a component that fetches a public Badgr URL, creates an `<img>` tag, and sets `src` and `alt` appropriately. Call it like this:

`<badge-view params="src: 'https://api.badgr.io/public/assertions/ZwxV7sqTTqa-r_vK51VsdA.json?v=2_0'"></badge-view>`

I'll let you style the component appropriately.

Our next step is to migrate any current evidence into Badgr badges, then replacing any references to that with URLs in the back-end API.

This component uses the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) for which we should probably add a polyfill. I can refactor it to use the existing JQuery REST code if you like, but I'm not as familiar with working with that, and `fetch` is a modern standard.

**Comment by joshdanielson** [comment]
@ndarilek I just issued you a new badge with two evidences:
1. a link to a user uploaded photo (professionals currently are asked to upload a photo of their license)
2. a link to the massage therapy's council validation

So there is one general 'narrative' and then narratives for each evidence.

Here's a link to the json: https://api.badgr.io/public/assertions/XmE3ncMeRP-1JLr7LfGd_w.json?v=2_0

As you mentioned, in the html we'll have:
- the badge image
- the badge name
- the badge description
- the general narrative
- link to evidence page with evidence narratives and supporting urls

I think it's fairly straight-forward, but let me know if you have any questions.

**Comment by ndarilek** [comment]
`<badge-view/>` now requests V2.0-style assertions regardless of what format checkbox is selected when the share link is generated. This has 2 advantages:
 * The error-prone step of remembering to check the correct box is no longer required. Without checking the correct version, badges wouldn't display correctly.
 * As long as Badgr generates newer versions of older assertions, we can upgrade our components across the board by changing their version expectations in one place.

**Comment by IagoSRL** [comment]
Pushed lot of progress, with user-badges loading at listingEditor and badge-add/edit connected, updates at credentials-add. Some error here and there but something can be tried.
The 'view details' link at listingEditor for each badge is linking now to the badge-edit rather than badge-view on purpose, since this last was not updated still (I suppose must be like the edit but without being a form, no buttons, just display the same data, right?).

**Comment by joshdanielson** [comment]
@iagosrl could you also try and get some unstyled evidence images to show up on the details? I wasn’t able to for some reason.

**Comment by IagoSRL** [comment]
Hi @joshdanielson. Current display for evidences is a list with links containing the 'narrative' text and the ID URL.
The problem with evidences is that not all return enough information to have something descriptive to display to the user; because of that, I filter the evidences to only display ones that have a narrative and ID properties; otherwise, the evidence just fails because no narrative property exist or empty link; I just completed the initial prototype code you have here that tried to use that both properties, but preventing some crashes when the data does not exist at some evidence; we can review which other interesting properties can be included for the 'evidence' object, like images, but seems that all the information is optional so lot of care needed to prevent crashes. Still, something related to that is what happened at the error you just commented at #746, will comment there the details, please let continue conversation there.

**Comment by IagoSRL** [comment]
Just about design: @joshdanielson your latest minor changes for CSS here have weird results, looking to me this way:
![screenshot-2018-4-4 edit your housekeeper listing - loconomics](https://user-images.githubusercontent.com/1070576/38299307-f2f03184-37f9-11e8-81fc-0637fa6ff8c6.png)

**Comment by joshdanielson** [comment]
@IagoSRL here is the collections URL I was using that threw an error: 

https://api.badgr.io/public/collections/fcfad6d9e51bd635c9c88248587dc035

**Comment by joshdanielson** [comment]
@IagoSRL it looks like it's just not converting it to 2.0. The "share" function on badgr does not give an option for 2.0 for collections (and the default for a badge is 1.0). I recall @ndarilek writing something to append those urls to change them to 2.0.

**Comment by joshdanielson** [comment]
@IagoSRL looking at the css, I think it's something to do with placing the classes in the div rather than the li tag. It gets confusing as the li tag is in listingEditor but the .styl file is in the component for BadgeViewer-card. Basically, I just want them to match the margins of the address and education cards (and also appear two in a row on larger screens).

**Comment by joshdanielson** [comment]
@IagoSRL just reviewing the evidence and remembering they are URLs as you stated. I just added a target="_blank" to them so they open in a new window. I am not sure about the error commented on #746, though. 

Do you mind polishing the css for badge-view? It doesn't seem to be too responsive and probably just needs some column classes. It's not meant to be anything more than factual so whatever you think looks good.:
![screen shot 2018-04-04 at 9 24 38 am](https://user-images.githubusercontent.com/1202838/38320737-3c4ba94a-37ea-11e8-9250-032c43688442.png)

**Comment by IagoSRL** [comment]
Yes, I keep the code from @ndarilek that touched the URL to force a call to v2, but reviewing it again is based on a RegEx that detected other version number and replace it by v2, on this case the problem is that the URL has not even parameter for version, but can quickly check that and add it if no parameters exist. That should fix the error.

**Comment by IagoSRL** [comment]
Fixed the versioning of links without a version parameter, now should work your link @joshdanielson

**Comment by joshdanielson** [comment]
@iagosrl tested and working! I added a v1.1 badge and it converted the url. I also added the collection again...it did not store the url as appended (with ?v=2.0 at the end of the collection) but displays fine. Not sure if it matters but wanted you to know.

**Comment by IagoSRL** [comment]
OK, it's fine. The URL is reviewed and patched any time is used to fetch data, but not stored. thanks

**Comment by ndarilek** [comment]
Yeah, let's avoid storing the URL with specific versions. If they ever
release a v3_0 badge and we want to use those features, I imagine doing
so would just be a component tweak away.
