### ISSUE TITLE
Display badges not issued by Loconomics

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#748]
## User Story
We want to be able to list badges earned outside of Loconomics by students so they can be displayed on their listing.
### Test Cases
- Students know what Badgr is.
- Students who have a Badgr account can easily allow Loconomics to see their badges.
- Students can choose what badges to display on their listing.

### To-do
- [ ] Make sure we can connect to the badgr API using a student OAUTH.
- [ ] Make sure we have a way for the student to enter their badgr info for us to have permission. 
- [ ] Make sure we filter badges to display only badges relevant to clients.

**Comment by ndarilek** [comment]
I've added a `<badge-collection/>` component to the branch.

To implement it, I modified `<badge-view/>` with the following behavior:
 * If called with a `src` parameter, the assertion data is retrieved and displayed.
 * If called with an `assertion` parameter, the contents of the `assertion` are set and displayed directly. No fetch is performed.

This latter case is not intended for external use. The point is that `<badge-collection/>` calls the JSON endpoint for the collection, gets a list of assertions, then iterates through them, reusing the `<badge-view/>` component.

We'll probably want some means of telling `<badge-view/>` whether to display a summary or all badge details. I imagine, when viewing a collection, that someone doesn't want to see every piece of badge evidence. We may also want to consider making the `<img/>` a link to the badge on Badgr, which I assume handles evidence display already.

But, unfortunately, I'm having issues passing the individual badges into each instance of the `<badge-view/>` component. What am I missing? I've added a few `console.log` calls, and it does appear to be getting a list of badges. Maybe I'm setting up the observables incorrectly, or the bind syntax I'm using doesn't support passing in objects?

Thanks.

**Comment by joshdanielson** [comment]
@ndarilek let's have @IagoSRL spend a few minutes reviewing this to see if he can answer your questions and we can discuss on the call Monday.

**Comment by IagoSRL** [comment]
@ndarilek I pushed a commit to the is746 branch fixing how params are given to a parameter, it should fix the problem you have.

Remember:
- Use `params` attribute when using a component to to provide parameters to the component constructor
- The content of `params` is actually an object without the brackets: you can pass two values as in `<badge-view params="assertion: $data, anotherParam: 'hello'"></badge-view>`
- Use `data-bind` attribute to use binding helpers on the component as usual
- Both attributes can be combined, as in `<badge-view params="assertion: $data" data-bind="visible: $data !== null"></badge-view>`
