### ISSUE TITLE
Student Sign-up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#761]
### User Story
My college is a great place to learn and obtain new skills.  My professors are caring and supportive.  I am signing up because I   believe that the marketing efforts of the Community College, will increase my ability to attract and secure potential clients.
#### Test Cases
- Student successfully signs up and their correct college is shown in their listing.
- Student successfully selects their field of study.
- Student's   data is captured correctly in metrics.
 
#### To-do
- [x] Make sure to include CCC colleges dropdown in sign-up form in HTML
- [x] Make sure to get list of colleges from Charles
- [x] Make sure to assign college, FieldOfStudyID to the user via POST API call when account created.
- [x] Make sure to create userEducation entry for student with institutionID, and Field of Study equal to the FieldofStudyName they chose from the dropdown with no begin or end study dates (they can edit that later
- [x] Add CCCUsers table with userID, InstitutionID, FieldOfStudyID, PlanExpirationDate
- [x] Populate CCCUsers table with sign-up data and set PlanExpirationDate to 180 days from signUp date

**Comment by joshdanielson** [comment]
@IagoSRL I've pushed everything I can for this issue and created a [Table Updates.txt](https://github.com/loconomics/loconomics/files/1608288/Table.Updates.txt) text document (you can change it to .sql after you download it...GitHub doesn't allow .sql to be updated) with all the database changes. I included comments. Review them and let me know of any doubts you have. I did NOT make any updates to the dev or live databases.

Assigning this issue to just you for now.

**Comment by joshdanielson** [comment]
@IagoSRL I added UserType to the CCCUsers table and a corresponding drop-down (with default to "student") on the sign-up page. I've noticed professors have been signing up and I assume this would be a good place for administrators (for future reporting) to sign up as well. We can think of what to do with professors and adminstrators in conjunction with the reporting. I don't think it makes sense for them to create a listing, but they may want to try it out. Not sure exactly what to do so we can wait to decide for now.

**Comment by joshdanielson** [comment]
@IagoSRL I tested the email sign-up and all is working perfectly. I got this error when clicking on "Sign up with Facebook":
![screen shot 2018-01-26 at 4 08 25 pm](https://user-images.githubusercontent.com/1202838/35465784-63246f46-02b3-11e8-9208-d03a17f89ec1.png)

**Comment by joshdanielson** [comment]
@IagoSRL I signed up from the home page (not landing page) and created a listing and then tried to change my plan and got this error:
![screen shot 2018-01-26 at 4 34 59 pm](https://user-images.githubusercontent.com/1202838/35466265-01f2ca70-02b7-11e8-8130-fcd6a9f16480.png)
![screen shot 2018-01-26 at 4 34 40 pm](https://user-images.githubusercontent.com/1202838/35466266-020ca72e-02b7-11e8-87ff-f3d0aa1b2780.png)

**Comment by IagoSRL** [comment]
The Facebook Connect will never work when tried on localhost per Facebook restrictions, can only be tested at *dev* and live

**Comment by joshdanielson** [comment]
@IagoSRL was thinking that could be the case. All else s
