### ISSUE TITLE
Student Plan

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#762]
### User Story
My college has provided the resources I need by securing access to the premium plan for the digital platform.  By   providing this benefit, I am able to launch my new venture with little to no out of pocket cost…that’s amazing!
#### Test Cases
- Students successfully access premium features.
- Students are not charged for CCC plan.
 
##### To-do
- [x] Make sure to create a premium plan for students with agreed features.
- [x] Make sure to give the plan an expiration date.
- [x] Make sure student is assigned to this plan via POST API call.
- [x] Make sure student is not asked to upgrade to non-CCC plan during the course.

**Comment by IagoSRL** [comment]
@joshdanielson I did this, with the new plan CccPlan (displayed "CCC Plan") and 6 months expiration date. Too, I updated the scheduled task that verify due date of plans.

I touched up the information displayed at the /account and /userFees activities, so relevant information is displayed for 'partnership plans' (like CCC Plan). Please test as me the three cases: user without plan, user with regular plan, student CCC Plan.

**Comment by joshdanielson** [comment]
@IagoSRL the user I signed up from the landing page had the plan set up correctly.

The user I signed up from the home page (not landing page) and created a listing (no plan) display fine.

However, when I tried to change my plan, I got this error:
![screen shot 2018-01-26 at 4 34 59 pm](https://user-images.githubusercontent.com/1202838/35466265-01f2ca70-02b7-11e8-8130-fcd6a9f16480.png)
![screen shot 2018-01-26 at 4 34 40 pm](https://user-images.githubusercontent.com/1202838/35466266-020ca72e-02b7-11e8-87ff-f3d0aa1b2780.png)

**Comment by IagoSRL** [comment]
Server error, fixed and uploaded

**Comment by joshdanielson** [comment]
@IagoSRL not sure if you uploaded this to the server but still getting the error.

**Comment by joshdanielson** [comment]
Still getting an error, may be the same, not sure:
![screen shot 2018-01-29 at 9 45 06 am](https://user-images.githubusercontent.com/1202838/35525377-2a7bdcd8-04d9-11e8-99a7-081f42a0743a.png)

**Comment by IagoSRL** [comment]
sorry, picking  manually files is error prone (there was two changed not just one). is up

**Comment by joshdanielson** [comment]
@IagoSRL working now, thanks!
