### ISSUE TITLE
Student Landing Page

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#763]
### User Story
I am new to the GIG economy, but I am confident that I have the skills to succeed.  I look forward to partnering with Loconomics to provide with the information I need to take advantage of the many features they have to offer to students like me.
#### Test Cases
- Students understand what Loconomics is and its offering.
- Through the self-employment pilot, students are able to develop and pursue a guided pathway based on skills they acquire through their college.
- Students understand creating a listing is required for the course.
 
#### To-do
- [x] Make sure to include information about Loconomics on the landing page.
- [x] Make sure to have a drop-down of the field of study to suggest job titles.
- [x] Make sure to include information about the partnership.

**Comment by joshdanielson** [comment]
@IagoSRL I just created a URL for this: http://localhost:8811/welcome/california-community-college-students.html. However, the signup box is missing. I remember this happening before and can't remember how to resolve it as it works on live (I tried logging out thinking that was it).
![screen shot 2018-01-04 at 3 07 36 pm](https://user-images.githubusercontent.com/1202838/34588348-5cdd6894-f161-11e7-9c21-d44d32f4b562.png)

**Comment by IagoSRL** [comment]
@joshdanielson I fixed the error with the carousel, actually was our code, but as expected, was a selector expression that was valid syntax previous jQuery v3 (now is stricker). Pushed to the branch, along with latest updates from master.

**Comment by joshdanielson** [comment]
@IagoSRL thank you!

**Comment by IagoSRL** [comment]
@joshdanielson Please, if the tasks on this issue are done, check them.

**Comment by joshdanielson** [comment]
@IagoSRL, @KyraHarrington is going to update the copy for this page on Tuesday or Wednesday. I'm assigning it to her.

**Comment by joshdanielson** [comment]
@IagoSRL I get this error when clicking on "Sign in" (if I already have an account). I'm thinking it's because it's not the regular build (I can't figure out how to do both at once). Terms and Privacy aren't working either.:
![screen shot 2018-01-26 at 4 11 55 pm](https://user-images.githubusercontent.com/1202838/35465821-b7b18314-02b3-11e8-9e6c-55bc309c88aa.png)

**Comment by IagoSRL** [comment]
I fixed a bug with  the Terms and Privacy links, while they now behave like login that only happens on localhost but is fine on the server (hope to fix this at another moment to have a dev environment more similar to server)

**Comment by joshdanielson** [comment]
@IagoSRL okay! I'll test again when on dev.

**Comment by joshdanielson** [comment]
@IagoSRL, @KyraHarrington and I revised the language today. There may be updates once we go into the testing phase with the colleges, but it's good to go for Monday.
