### ISSUE TITLE
List External Platforms by Job Title

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#765]
### User Story
I want to see in the Loconomics App external opportunities specific to my job title so I can focus my efforts on platforms where I'll find work.
#### Test Cases
- Student sees platforms they can list their services based on their job title.
- Student can link off to platforms.
- Student can find these opportunities in the app.
 
#### To-do
- [x] Make sure to include "Market yourself externally" section.
  - new activity created named 'market-externally'
- [x] Make sure to list all the platforms where they can find work.
  - new component created named 'external-platform-suggestions-list'
- [x] Make sure to make the list specific to the job title.
  - dummy data included in component and [actual data being populated](https://docs.google.com/spreadsheets/d/1c6IcwM9uNCcs-81zFHzRRQPzib39u05q4NavikelXCc/edit?usp=sharing) by @KyraHarrington.
- [ ] Create data models
- [ ] Create database tables
  - Platform
  - JobTitlePlatform
- [ ] Create SQL query for suggested platforms specific to the user and their job titles (including the -1 generic job title) ensuring listings they already have created in UserExternalListing are not included in the suggestion list.
- [ ] Create api calls

**Comment by joshdanielson** [comment]
@IagoSRL this issue is working on the front-end. I listed the remaining tasks (they could use better wording so please revise). Assigning to you.

**Comment by joshdanielson** [comment]
`INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 2, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 3, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 4, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 5, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 6, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 7, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 8, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.JobTitlePlatform (JobTitleID, PlatformID, LanguageID, CountryID, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (-1, 9, 1, 1, '2/2/2018', '2/2/2018', N'jd', 1);
`

**Comment by joshdanielson** [comment]
@IagoSRL I just committed the above on dev. @KyraHarrington is working on more and will post them this afternoon.
