### ISSUE TITLE
View External Platform Info

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#766]
### User Story
I want to know the pros and cons of each platform for external job opportunities so I can know the ins and outs of signing up.
#### Test Cases
- Student knows how commissions and fees work with a platform before linking off to it.
- Student knows what makes a platform beneficial before linking off to it.
- Student knows how to differentiate themselves on a platform before linking off to it.
- Student knows negative aspects of a platform before linking off to it.
#### To-do
- [x] Make sure to list commissions the platforms charge.
- [x] Make sure to list some benefits specific to the platform.
- [x] Make sure to list helpful tips on creating a listing specific to the platform.
- [x] Make sure to summarize anything the student should be aware regarding the platform's terms of the service.
- [x] Populate Platform table with real platform information

**Comment by joshdanielson** [comment]
@IagoSRL this should be working on the front-end. @KyraHarrington is working on the actual data for the Platform table, but there is dummyData to test it out.

**Comment by joshdanielson** [comment]
`INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (1, 1, 1, N'Loconomics', N'', '', '', '', '', '', N'', N'', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (2, 1, 1, N'Thumbtack', N'Marketplace for local services', 'Thumbtack is a service that connects people with local professionals for any project on their list.', 'Pay-per-quote model where you pay to send quotes to customers. Each quote costs anywhere between 2 to 9 credits, depending on the type of service the customer is looking for.', '["Potential to meet new clients"]', '["Money spent on credits may not outweigh money earned through gigs"]', '["Only bid on jobs that have a high likelyhood of turning into a booking","Use it to build ongoing clients"]', N'https://www.thumbtack.com/pro', N'https://www.thumbtack.com/login', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (3, 1, 1, N'TaskRabbit', N'Marketplace for general tasks', 'Taskrabbit connects you to safe and reliable help in your neighborhood.', 'TaskRabbit takes a 30% service fee. A 7.5% Trust & Safety is also added to the total of the task.', '["Freedom from the constraints of a 9-to-5 office job"]', '["Difficulty finding enough hours", "Pay can be insufficient (hourly average is $18)"]', '["Perform a variety of tasks to build a reputation"]', N'https://www.taskrabbit.com/become-a-tasker', N'https://www.taskrabbit.com/login?source=header', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (4, 1, 1, N'99designs', N'Marketplace for graphic designers', 'Connecting businesses with talented freelance designers.', '$0 sign-up fee, 20% commission if your design is chosen. ', '["Global demand","Potential to meet new clients","Build portfolio"]', '["Spec work: you only get paid out if your design is chosen"]', '["Enter many contests to build a reputation","Repurpose designs to multiple clients if they fit the criteria"]', N'https://99designs.com/signup?from=%2Fuser%2Fgetstarted', N'https://99designs.com/login', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (5, 1, 1, N'Crowdspring', N'Marketplace for graphic designers', 'Connecting businesses with talented freelance designers.', '$0 sign-up fee, 20% commission if your design is chosen. ', '["Global demand","Potential to meet new clients","Build portfolio"]', '["Spec work: you only get paid out if your design is chosen"]', '["Enter many contests to build a reputation","Repurpose designs to multiple clients if they fit the criteria"]', N'https://www.crowdspring.com/register/', N'https://www.crowdspring.com/login/', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (6, 1, 1, N'Designcrowd', N'Marketplace for graphic designers', 'Connecting businesses with talented freelance designers.', '$0 sign-up fee, 20% commission if your design is chosen. ', '["Global demand","Potential to meet new clients","Build portfolio"]', '["Spec work: you only get paid out if your design is chosen"]', '["Enter many contests to build a reputation","Repurpose designs to multiple clients if they fit the criteria"]', N'https://www.designcrowd.com/registration', N'https://www.designcrowd.com/login', '2/2/2018', '2/2/2018', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (7, 1, 1, N'Freelancer', N'Marketplace for graphic designers', 'Hire expert freelancers for any job, online.', 'You bid on open projects. Plans start at $9.95 /month and allows you to bid on 100 projects /month. More expensive plans will lower commission. ', '["Global demand","Potential to meet new clients"]', '["You have to pay to get more visibility",''Money spent on credits may not outweigh money earned through projects"]', '["Start with the free membership and upgrade after making money and getting reviews. This will allow for more bids and lower commissions."] ', N'https://www.freelancer.com/signup', N'https://www.freelancer.com/login', '2/2/2018', '2/2/2018', N'jd', 1);
`

**Comment by joshdanielson** [comment]
@IagoSRL see insert statements above I just executed on Dev. There will be more coming from @KyraHarrington this afternoon that I will post here.

**Comment by joshdanielson** [comment]
Updated FeesDescription to be JSON:
`UPDATE dbo.Platform SET FeesDescription = '["Pay-per-quote model where you pay to send quotes to customers.", "Each quote costs anywhere between 2 to 9 credits, depending on the type of service the customer is looking for."]' WHERE PlatformID = 2 AND LanguageID = 1 AND CountryID = 1;
UPDATE dbo.Platform SET FeesDescription = '["TaskRabbit takes a 30% service fee.", "A 7.5% Trust & Safety is also added to the total of the task."]' WHERE PlatformID = 3 AND LanguageID = 1 AND CountryID = 1;
UPDATE dbo.Platform SET FeesDescription = '["$0 sign-up fee.", "20% commission if your design is chosen."]' WHERE PlatformID = 4 AND LanguageID = 1 AND CountryID = 1;
UPDATE dbo.Platform SET FeesDescription = '["$0 sign-up fee.", "20% commission if your design is chosen."]' WHERE PlatformID = 5 AND LanguageID = 1 AND CountryID = 1;
UPDATE dbo.Platform SET FeesDescription = '["$0 sign-up fee.", "20% commission if your design is chosen."]' WHERE PlatformID = 6 AND LanguageID = 1 AND CountryID = 1;
UPDATE dbo.Platform SET FeesDescription = '["You bid on open projects.", "Plans start at $9.95 /month and allows you to bid on 100 projects /month.", "More expensive plans will lower commission."]' WHERE PlatformID = 7 AND LanguageID = 1 AND CountryID = 1;
`
