### ISSUE TITLE
External Listing Editor

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#767]
### User Story
I want to store information of each external listing I create so I can keep track of where I'm listed.
#### Test Cases
- Student can enter in high-level info about external listings they create including platform, listing URL(if available), personal notes, job title
- Student can see any external listings they've entered and click on links to each platform.
- Administrator can filter by job title.
- Administrator can filter by platform.
#### To-do
- [x] Make sure to include a section "Listings elsewhere" in "Your Listings"
  - 'external-listing-list' component created and added to /yourListings
- [x] Make sure to include a button to add a listing outside of Loconomics.
  - 'Add listing' button link added to 'external-platform-info' component
- DISCARDED Make sure to include a form where a student can enter the URL, a title,
- [X] Make sure to include a notes field for each external listing.
  - 'external-listing-editor' component created
- DISCARDED: Make sure to show the student how many listings they have on each platform.
- [x] Make sure to include a link to the listing so they can log in and manage.
  - 'SignInURL' included in 'external-listing-viewer' component in 'external-listing-view' activity.
- [X] Make sure to include a search/dropdown to map a Loconomics job title to the external listing.
 - needs to be added to 'external-listing-editor' component
 - we will likely want to store both the jobTitleName and jobTitleID
 - See [UserExternalPlatform table mockup](https://docs.google.com/spreadsheets/d/1c6IcwM9uNCcs-81zFHzRRQPzib39u05q4NavikelXCc/edit?usp=sharing)

**Comment by joshdanielson** [comment]
@IagoSRL assigning this to you. Really, I think the only issues are in the external-listing-add and external-listing-edit activities (and corresponding components) with the following:
- Undefined showing for platformName in both page titles and listingTitle (the default value)
- Values not being shown for existing external listings when being edited

**Comment by joshdanielson** [comment]
Closing.
