### ISSUE TITLE
Earnings Tracking

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#776]
## Epic Story
As a student, I want to track my income earned from each job so I can meet course requirements, track my progress and be ready for tax time.

**Comment by IagoSRL** [comment]
@joshdanielson Some of the work on this epic I included in just released v1.8.4:

- [x] external listings: changed deletion of a listing to soft delete (fixes cross references errors).
- [x] external listings: auto add job titles to user listings/profile from titles selected at external listings. keeps related local cache in sync.
- [x] earnings editor: preselect jobtitleid on editing
- [x] earnings editor: preselect listingid on editing
- [x] earnings editor: includes job titles autocomplete below the user listing titles so can pick another one that gets
  [x] - automatically added to user listings/profile
  [x] - automatically added to the external listing included in that earnings entry
  [x] - any of that interacts with the cache data in the App to keep data up-to-date (keep in sync).
- [x] earnings editor:  includes suggested platforms, the selected one will be added as external listing as part of the process (with the job title selected at the earnings registered as of that new external listing). Keep related local cache in sync.
- [x] earnings editor: fixed: edit/plus buttons must be disabled on locked
- [x] earnings editor: fixed: first time, looks like date is selected to current date, but no one date is actually selected when reaching the summary making the saving to fail.
- [x] earnings editor: refactored part of steps management, now independent of stuff specific to earnings editor (looks reusable now), that fixes a couple bugs on edge cases and allowing to implement:
  - [x] when editing an entry (at edit/copy mode or after reach summary on add mode) rather than the 'go back step' button should have a ‘go back to summary’ (even the first step).
- [x] earnings editor: 'go back' buttons/links should behave as one (forgotten 'href' attr)
- [x] earnings editor: allows deletion (soft delete).
- [x] earnings editor: is allowed to preset the userExternalListingID when adding a new one (*there is no link using it still, but the feature is there, @joshdanielson we can use the link /earnings-add/the-external-lstingID at the external listing if you want an 'add earnings' button there).

@joshdanielson Aside with this, I fixed the caching (#794), minifying (#795) and a clients/users bug (#799), and released to *dev* and *live* a few minutes ago. I tested and seems stable (so I trusted to release it :-) but you know, double check.

I was working on the clients at earnings, there I found the clients bug, but is not complete and preferred to release the rest.

**Comment by IagoSRL** [comment]
Closed issues that were already completed, some released as of 7.15.x and latest changes in upcoming 7.16.
Added to the Epic the issues #829 #830 created for pending tasks.
