### ISSUE TITLE
Create form to capture earnings

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#777]
### User Story
I need a simple form to enter the required information for each gig booked outside of Loconomics so I can keep track of earnings.

#### Test Cases
- Student can fill out form with confidence they're entering data correctly.
- Student can fill out form within two minutes.
- Student can edit information if they make a mistake.
 
#### To-do
- [x] Make sure the form includes dropdown with their external listings with the ability to "Add new external listing" and option for "Other".
- [x] Make sure the form includes earnings.
- [x] Make sure the form includes description of job.
- [x] Make sure the form includes date of payment.
- [x] Make sure the form includes hours worked.
- [x] Make sure the form can be edited.

**Comment by IagoSRL** [comment]
@joshdanielson I found now that info requested in this issue was never added to the editor, please confirm if must be added (per approved prototypes), or left for later review:
- commissions
- payment processing fees
- date of job (only date paid is included, and is used for filtering and summary of totals)

Another details:
- There is option "Add new external listing" by chosen other suggested platforms, but not for more platforms (not suggested ones) still.
- Found that, since the Loconomics listings are not external listings, cannot be chosen to add earnings. Should be added in a different way? Should we combine external-listings with (Loconomics) listings to add earnings for?

**Comment by IagoSRL** [comment]
Moved to QA anyway, I think that doubts can be details for a follow-up issue, iterating the feature with enhancements (to add some of the commented fields is not difficult, if must exists per agreed prototypes)

**Comment by joshdanielson** [comment]
@IagoSRL those fields aren't needed (too complicated to find and enter and date of job isn't too important for tax purposes). I removed them from the requirements. Closing.

**Comment by IagoSRL** [comment]
OK, makes sense.

Please, don't forget to review the last two things, copying here (new issues is a good fit):
- There is option "Add new external listing" by chosen other suggested platforms, but not for more platforms (not suggested ones) still.
- Found that, since the Loconomics listings are not external listings, cannot be chosen to add earnings. Should be added in a different way? Should we combine external-listings with (Loconomics) listings to add earnings for?

**Comment by joshdanielson** [comment]
@IagoSRL I created #829 and #830. May need some revision.
