### ISSUE TITLE
Create reminders to enter earnings weekly/monthly

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#779]
### User Story
I need reminders to enter my earnings weekly/monthly so I don't forget to do it.

#### Test Cases
- Student is prompted to enter their earnings.
- Student is motivated by the reminders.
- Student can easily dismiss the reminder if they have no earnings.
- Student is not reminded after they've entered them.
 
#### To-do
- [x] Make sure email and alert reminders are set weekly/monthly.
- [ ] Make sure the alert is not turned off until weekly/monthly earnings are recorded.
- [ ] Make sure there is an option to indicate "No outside earnings this week" that can be clicked on the reminder email/alert.

**Comment by joshdanielson** [comment]
@IagoSRL I was on a call today and Charles from the colleges mentioned this. I think he thinks it's already implemented. Do you mind doing this one after the badges is complete? The template is complete. Let's set the reminder to monthly on the 1st. And only for CCCUsers at this time.

**Comment by IagoSRL** [comment]
I have mostly done the email reminder, but some questions:
- Should we send email to all CCCUsers (of type student) or only ones that didn't have entered for the last weeks (based on createdDate rather than payment date)? (maybe is trying to guess to much?)
- The template code said to sent it two times in a month, days 1 and 15 that should be fine so did it that way; but is quick to change. Also, the reminder sends at 07:00 AM.
- Since the issue says 'alert', should we have an UserAlert additionally to email? I suppose not, since that ones are displayed just at the listingEditor that may not be so useful. It's different if we had an alert/notifications system visible across all the app, like a badge near the user menu on desktop.
- If we only have the email as reminder, there is no need for a button to 'dismiss', because there is no 'alert/notification' to dismiss (user can just trash the email).

**Comment by joshdanielson** [comment]
@IagoSRL let's start with the most simple and add more if it's needed as I think the requirements I had were a little overkill. Let's do this:
- Send to all CCCUsers of type student and ignore any earnings/payments entered
- let's start with days 1 and 15 at 7:00am (that seems like a useful but not annoying reminder)
- I think email is enough for now. When we get regular alerts on the dashboard, then we can implement this one.
- no dismiss for now...again, don't think two emails is too annoying

Sound good? I think it'll be more than sufficient and lays the groundwork if/when we add more.

**Comment by IagoSRL** [comment]
@joshdanielson I think I will left this just as is, sending the email reminders just to all CCCUsers every two weeks. Then we can polish, like querying if they had already some entry in the period and some notification in the webapp.

**Comment by IagoSRL** [comment]
OK, just what I sent at same time! Will upload to *dev* so can be tested.

**Comment by joshdanielson** [comment]
@IagoSRL see my comments above but we're in agreement. All 'student' users, just to clarify.

**Comment by IagoSRL** [comment]
Pushed to *dev*, realized that is not so easily testable so I temp tweaked the task times to be now and forced the schedule task to run now, so the unique user at *dev*, 899 'JoshuaStudent' (student@loconomics.com) should get an email; @joshdanielson let me know if you get it and links properly to earnings-add.

**Comment by joshdanielson** [comment]
@IagoSRL I don't have an alias set up for student@loconomics.com. I may be at my limit but let me try to add it now and will let you know when it's live.

**Comment by IagoSRL** [comment]
Oh, thought was, I can add it myself and test, and a record for your other user without needing to touch that; then I can remove that testing records.

**Comment by joshdanielson** [comment]
@IagoSRL I just added it so please re-run the task.

**Comment by IagoSRL** [comment]
OK, done!  I didn't added the others still, so just the student@loconomics.com

**Comment by IagoSRL** [comment]
I added my user and one yours (540, with your loconomics.com email) and run it; it says 3 emails were sent and I get mine already.

**Comment by IagoSRL** [comment]
I resent to you my received email, tested the link too. There is an issue with direct links (any) if user has to log-in, but that's another issue. Closing this since my testing worked.
Removing that two testing records too: for the record, the were:
```sql
insert into cccusers (userid, usertype) values (141, 'student');
insert into cccusers (userid, usertype) values (540, 'student')
```

**Comment by joshdanielson** [comment]
@iagosrl finally received and working.
