### ISSUE TITLE
Create earnings summary

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#780]
### User Story
I want to see a summary of my earnings and query them with general parameters.

#### Test Cases
- Student can see a quick summary of their YTD earnings
- Student can filter earnings by different time periods
- Student can filter earnings by job title
- Student can filter earnings by platform
- Student can see important earnings metrics 
- Student can link to see a transaction history
 
#### To-do
- [x] Make sure the summary includes a time period dropdown filter for This year, This month, This quarter, Last month, Last quarter, Last year and include options in a list ---Month---, ---Quarter---, ---Year--- with present values.
- [x] Make sure the summary includes a total for the period, paid out earnings, and expected earnings 
- [x] Make sure the summary includes hours worked, average hourly rate, bookings
