### ISSUE TITLE
Add 'External Listings' VOC Element

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#782]
### To-do
- [x] Create externalListing VOC element and ID in app JS with ID 21
- [x] Add to app-inline-side-menu to corresponding activities
- [x] Add new element, with ID 21, to dev and live databases:
`INSERT INTO dbo.VOCElement (VOCElementID, LanguageID, CountryID, VOCElementName, ScoreStartValue, ScoreMidValue, ScoreEndValue, ScoreStartLabel, ScoreMidLabel, ScoreEndLabel, CreateDate, UpdatedDate, ModifiedBy, Active) VALUES (21, 1, 1, 'External Listings', null, null, null, null, null, null, '2018-01-25 00:00:00.0', '2018-01-25 00:00:00.0', 'jd', 1);
`
