### ISSUE TITLE
Add "Earnings Tracking" VOC Element

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#783]
### To-do
- [x] Create earningsTracking VOC element and ID in app JS with ID 22
- [x] Add to app-inline-side-menu to corresponding activities
- [x] Add new element, with ID 22, to dev and live databases:
`INSERT INTO dbo.VOCElement (VOCElementID, LanguageID, CountryID, VOCElementName, ScoreStartValue, ScoreMidValue, ScoreEndValue, ScoreStartLabel, ScoreMidLabel, ScoreEndLabel, CreateDate, UpdatedDate, ModifiedBy, Active) VALUES (22, 1, 1, 'Earnings Tracking', null, null, null, null, null, null, '2018-01-25 00:00:00.0', '2018-01-25 00:00:00.0', 'jd', 1);
`

**Comment by IagoSRL** [comment]
This was done and merged to master days ago, ready for release, closing.
