### ISSUE TITLE
Revise category photos

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#797]
### User Story
As a client, I like to see some visuals to aid me in my search process.

### To-do
- [ ] Determine where photos are needed
- [ ] Include photos in solutions data tables
- [ ] Store photos on server with reference to file in API
- [ ] Choose photos

#### Photos
Dog care: https://pixabay.com/en/four-dogs-pack-papillon-hybrids-1919152/
Child care: https://pixabay.com/en/mother-baby-child-garden-home-1150056/
Grooming: https://pixabay.com/en/puppy-bath-foam-dog-shampoo-1022421/
Self care: https://pixabay.com/en/weights-pilates-girls-1948837/
Transport: https://pixabay.com/en/cycling-handlebars-woods-bicycle-828646/
Office: https://pixabay.com/en/office-tax-business-finance-620822/
Celebration: https://pixabay.com/en/muffins-baked-pastries-cup-cake-2652012/
Senior: https://pixabay.com/en/ball-people-old-elderly-man-2585603/
Senior: https://pixabay.com/en/architecture-house-window-wall-2560773/
