### ISSUE TITLE
Service professional clients had null languageID-countryID throwing errors

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#799]
### Long Description
Inserting a completely new service professional client has not set the languageID and countryID fields, left as null, while at some point the method UserProfile.Get added that fields to the query, being assigned to non-nullable properites. That internal API is used by the /clients API, then throwing errors on that cases.

### Tasks
- [x] Insert a new user as a result of client insertion request must set-up user languageID and countryID as the from the current locale in use.
- [x] All existent users with null value at that fields must be updated to 1, 1 (the only used values until now).
- [x] That fields must be not-null at database.
- [x] Check other code doesn't makes the assumption of allow nulls there.

**Comment by IagoSRL** [comment]
I completed this and included in the new release to *live*
