### ISSUE TITLE
Create data structure and content for Specializations

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#812]
## To-do
- [x] Create Specialization table (includes SolutionID for mapping purposes)
- [x] Map Specializations to Solutions
- [x] Create UserListingSolution table
- [x] Create Foreign Keys for UserListingSolution and Specialization

**Comment by joshdanielson** [comment]
@IagoSRL can you add the foreign keys for the tables above? I populated specializations for Massage Therapy and Cleaning so we can fully implement. I also included the "Approved" field (default 0) so we can only display to other users and in search filters those approved.

**Comment by IagoSRL** [comment]
Fixed the PK for Specialization table (removed SolutionID; was impossible to create foreign keys with that), added foreign keys for UserListingSolution, Specialization and UserListingSpecialization (scripts 'is796 - F - *')

**Comment by IagoSRL** [comment]
I applied that scripts to *dev*. Had to update a couple of scripts (adding correct PK directly at the 'create table' script)

**Comment by joshdanielson** [comment]
@IagoSRL I reviewed this in the dev database and all looks good (PKs, FKs, data). Not sure what other QA I can do. If none, you can close.
