### ISSUE TITLE
Set-up partner admin account type and privileges

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#815]
## User Story
As Loconomics, we want to ensure that only admins with our partners have the ability to access their constituents' data and no one else's.

### To-do (Needs revision)
- [ ] Add to CCCUsers table Privileges field. Potential values are "collegeLevel" and "full"
- [x] Make sure access to the API is authenticated only relevant privileges are granted to each user
- [x] Make sure student's privacy rights are maintained by ensuring personally identifiable fields are not accessible to those who should see them.

**Comment by IagoSRL** [comment]
@joshdanielson Please explain me the point `Make sure student's privacy rights are maintained by ensuring personally identifiable fields are not accessible to those who should see them`. If we return the userID in the detailed report, that's enough to get all public user info, that's fine as far as the report is only available to CCC admins/collegeAdmin/reportAdmin?

**Comment by joshdanielson** [comment]
@IagoSRL good question. We should have userID, StudentID, Date of Birth, and gender but no names. So they can match up the student with the available information.

**Comment by IagoSRL** [comment]
So should I include studentID and date of birth to the current detailed report? (did you tried the CSVs? is it fine for the rest?)

**Comment by joshdanielson** [comment]
@iagosrl yes, include. I couldn't try as it wouldn't load (see other issue).

**Comment by IagoSRL** [comment]
I included both fields

**Comment by IagoSRL** [comment]
(and pushed to dev and live)
