### ISSUE TITLE
Create Report Filters

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#816]
## User Story
I want to be able to filter the data so I can analyze trends.

### Test Cases
- Administrator can filter by day, week, month, term, year.
- Adminstrator can filter by college.
- Administrator can filter by job title.
- Administrator can filter by platform.
- Administrator can filter by Taxonomy of Programs (TOP) code
 
### To-do
- [x] Make sure to include college name/ID in the data export.
- [x] Make sure to include job title name/ID in the data export.
- [x] Make sure to include day, week, month, term, year in the data export.
- [x] Make sure to include platform name/ID in the data export.
