### ISSUE TITLE
Partner client account creation

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#822]
## User Story
As a potential client, I want to create a listing with general information about my business/department so students can learn about us before applying.
### Test Cases
- Small business partners/Internal CCC departments can easily enter their name, description, key contact person, logo, website.
- Small business partners/Internal CCC departments feel their listing communicates well who they are.
 
### To-do
- [x] Make sure to the listing asks for the small business'/department's name.
- [x] Make sure to the listing asks for the small business'/department's description.
- [x] Make sure to the listing asks for the small business'/department's key contact person.
- [ ] Make sure to the listing asks for the small business'/department's logo.
- [x] Make sure to the listing asks for the small business'/department's website.

**Comment by IagoSRL** [comment]
I'm thinking a bit more on this: rather than add more specific stuff to the landing and signup (I was working on that to recognize them as 'gig posting partners' internally), just add/replace a button at the 'welcome' activity (is't the start point for onboarding after signing-up) so there is a 'post a gig' button.
We have this now there:
![imagen](https://user-images.githubusercontent.com/1070576/40679308-1b0a5e06-6383-11e8-9a2e-4af8ffc365c0.png)

Maybe is too service-professional specific the language, even if this displays for all kind of users. Just an idea

**Comment by joshdanielson** [comment]
@IagoSRL I don't think we can add another button to the welcome pop-up as it's pretty busy already...thinking out loud about your first comment (specific onboarding) and I think we could:
- add an activity /clientBusinessInfo (like serviceProfessionalBusinessInfo) but add to it the logo and description
- that be a step in the posting but skipped if completed (and shown in edit mode). 

What do you think?

**Comment by IagoSRL** [comment]
Added 'client' cccUserType to signup at server (uploaded to *dev*) and added Signup component to ccc-partners with that type preset.

**Comment by joshdanielson** [comment]
@IagoSRL still not seeing the signup component on the landing page on dev:
![screen shot 2018-06-01 at 10 14 29 am](https://user-images.githubusercontent.com/1202838/40853961-a093142a-6584-11e8-9f69-057751e3d462.png)

**Comment by IagoSRL** [comment]
didnt' pushed to dev but is on branch.

**Comment by joshdanielson** [comment]
@IagoSRL I'm on my laptop and can't find the command for building the landing pages and also seeing I never put it in the docs. Can you post it here, and I'll add it to the docs once and for all?

**Comment by IagoSRL** [comment]
Building landing pages: `grunt build-landingPages`.
Make that build available at web folder to prepare upload: `grunt publish-landingPages`
Working just on landing pages: `grunt atwork --target=landing_pages`

**Comment by joshdanielson** [comment]
@IagoSRL thank you! updated in the App Quick Start Guide. Will test the sign up now.

**Comment by joshdanielson** [comment]
@IagoSRL tested the sign up and it shows up as "client" in CCCUsers table successfully. I do think we should ask them for their nearest college and add a checkbox for them posting a project on behalf of their business, but I guess it's customizing the sign up module a bit as we'd have to change the language. 

Now what to do with the welcome. Thinking more, this landing page (for now) will be for these clients/partners to post projects (since the marketplace isn't active). What do you think about sending them directly to /posting after they sign up with a stop at the /clientBusinessInfo (if they check the business box)? It's the action we want them to do. I'll have to tweak the landing page info a bit.

Other minor things with the sign up box if we can customize it a bit more:
- change "Sign up" to "Get started" (seems better for clients on a landing page)
- change the sign up button (Get started) to the same blue I have on the other buttons. Not sure what to do with those buttons...will probably have to remove since they won't go anywhere. 

Let's chat after the call and clarify anything left as I know I didn't make things clear...I didn't have anyone to talk them through with (sorry).

**Comment by IagoSRL** [comment]
About onboarding partner clients, what I though and I'm working on actually is:
- adding [users].IsOrganization bool column, false by default, but set as 1 for who sign-up from ccc-partner checking that new checkbox ('on behalf my organization/business/whatever').
- add a step only for IsOrganizations at onboarding, just after 'publicContactInfo' (that is showed to everybody), asking for the organization info (the fields listed on this issue).
- redirect users to the step after the 'welcome', that is just 'publicContactInfo' (I think that data about the person/user is still important to get from this users).
- after onboarding, to keep it generic (less specific code/switches): tweak current modal window displayed after to add a button to 'post a project'.

**Comment by IagoSRL** [comment]
Opened #869 for the organization logo, less priority. Closing as all is done here.
