### ISSUE TITLE
Map solutions to Job Titles

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#825]
## To-do
- [x] Create JobTitleSolution table
Maps solutions to job titles. Some solutions will be mapped to multiple job titles.
- [x] Add relevant foreign keys to table
- [x]  Populate JobTitleSolution table

**Comment by joshdanielson** [comment]
Create JobTitleSolution table completed and sql executed on dev database.

**Comment by joshdanielson** [comment]
@IagoSRL JobTitleSolution needs foreign keys added.

**Comment by IagoSRL** [comment]
Added FKs to JobTitleSolution; and too to JobTitlePlatform I found didn't have it and needs the same.

**Comment by joshdanielson** [comment]
@IagoSRL I reviewed this in the dev database and all looks good (PKs, FKs, data). Not sure what other QA I can do. If none, you can close.

**Comment by IagoSRL** [comment]
Thanks, closing
