### ISSUE TITLE
Create Ability to Add External Listing from "Other" platform

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#829]
### To-do
- [ ] Add generic platform ID to Platform table (-1?) with name "Other"
- [ ] Add "Other Platform" to options in earnings-editor with field for "UserExternalListing.Title" with placeholder, "e.g. My Listing on X Platform"
- [ ] Create new entry in UserExternalListing table with generic ID, job titles, and the Title the user created"
