### ISSUE TITLE
Update earnings entry to capture solution instead of job title

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#838]
### User Story
As a professional, I need to report to the tax authority my earnings based on business activity and not necessarily job title. 
#### To-do
- [ ] Let professional choose a solution instead of a job title in earnings-editor
- [ ] Create SolutionID field in UserEarningsEntry table 
- [ ] Manually update any user entries prior to change
- [ ] Remove JobTitleID field
