### ISSUE TITLE
Bug S2: Work Photo error message unclear

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#863]
### Long Description
When users enter a caption when uploading their work photos, the character limit warning message is unclear. @situatedbit had a character limit feature that told users how many they had left but the code was hidden in August 2017 as it wasn't accessible.

### To-do
- [x] Increase varchar limit to 150 in dev and live databases
- [ ] Revise error language to say "Your caption is XX characters over the limit – please edit and save again" 
- [ ] Revie character limit code to see if it can be made accessible easily

### Screenshots
![photo-caption-1](https://user-images.githubusercontent.com/1202838/40011879-f4476be6-575d-11e8-9ea1-ecc8f06821f5.png)
![photo-caption2](https://user-images.githubusercontent.com/1202838/40011880-f47199ac-575d-11e8-99b2-83ac17d8ec3b.png)

**Comment by joshdanielson** [comment]
@IagoSRL this should be good enough for now. I increased the size to 150 (I had 100 but then tested and went over right away). Let's focus on this after finishing the remaining elements unless I get more feedback on it.
