### ISSUE TITLE
Upgrade Braintree SDK and .Net Minimum version

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#87]
Required by a notice from Braintree, we must to upgrade to more recent version of their SDK in order to keep connections to its servers using TLS 1.2 or above (forbidding previous secure connections), before the year ends.

More at the document [Updating Your Production Environment to Support TLSv1.2](https://www.braintreepayments.com/blog/updating-your-production-environment-to-support-tlsv1-2/)

Seems easy once update the library is just copy a new version, but there is a major version jump, from 2 (we are using) to 3, and this ones introduces incompatibilities. Lucky, seems to not require code changes, just update to the most recent version of Microsoft .NET, the 4.6.2.
We are using 4.0 at development, but the server is already running 4.6 and all seems fine (good!), so we just ensure to update docs and our local dev environments to use 4.6.

## Tasks
- [x] Update docs about minimum .NET version
- [x] Notify back-end developers to upgrade their systems to .NET 4.6 or above. Document any problem or difficulty.
- [x] Update Braintree SDK to latest 3.x version. Test everything keep working.
- [x] If Release 1.2 not before end of January 2017, we may need to quick move this change to *live*.

**Comment by IagoSRL** [comment]
Fixing a couple of details of initial commit:

Braintree stop working with pre-TLS1.2:
- at sandbox environment on December 13, 2016 (is not already working, confirmed by @joshdanielson 
- at production environment on January 31, 2017  (and not 'before end the year' as I commented)

**Comment by IagoSRL** [comment]
First thing: Happy New Year!  No rush with this, if you are in holiday, left this for next week ;-)

---------------------

Updated Braintree version to 3.3, uploaded to *dev*.

I updated minimum software version of .NET Framework to 4.6.2, since latest Braintree requires 4.5 and upper and to better match what's in the server (is the newest .NET version available today). I updated [the docs](https://github.com/loconomics/loconomics/blob/master/docs/Backend%20Development%20Environment%20Setup%20Guide.md), some notes about the upgrade (for those coming from previous version and Windows 7-8), and some small additions for VS and SQL.
@situatedbit, please check and let me know anything that you find wrong or not clear. If I remember, you have a Windows 10 so you have already v4.6.2 and don't need to do changes on your system, but just in case.
