### ISSUE TITLE
Bug: User created by a Lead Generation API keeps partially inactive after signup

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#879]
### Long Description
An user has being generated as a 'subscriber' after using a Lead Generation component, so its specific API created a user with AccountStatusID of -1 ('subscriber').

At some point, the user has access to the site as any signed up user (still to determine if used the signup process or could have circumvent that), but the status is still the same and several queries check that should be equals 1 as a way to ensure user is active and publicly available. That leads to calls to the /users API to return a not found error, that happens as soon as the entering the listingEditor activity that uses still that public API to get part of the logged user profile data.

### Source
This happened to a real user and was fixed by manually setting the status ID in the database.

### Tasks
- [x] Research how user went from Lead Generation to a logged user capable of starting setting up a service professional profile.
- [x] Locate the paths that can lead to a situation where we must upgrade the status automatically from subscriber (-1) to active (1).
- [x] Implement fixes with care of not enable the user without properly going through a signup/accept terms/onboarding.

**Comment by joshdanielson** [comment]
@IagoSRL I tried to recreate that user's steps (there were many). Here they are:
- Signed up for the newsletter and checked "I provide local services"
- Then I tried to "Sign up" and got this message
![screen shot 2018-08-08 at 1 57 51 pm](https://user-images.githubusercontent.com/1202838/43864244-0487b8ae-9b14-11e8-8c73-d002bc0716bb.png)
- I checked my email that asked me to Activate my email that only brought me to a sign-in page (**It should automatically ask the user for a password with their email address pre-populated):
![screen shot 2018-08-08 at 1 59 36 pm](https://user-images.githubusercontent.com/1202838/43864241-044d0cc2-9b14-11e8-8942-9549bf22b707.png)
- I logged in with the same email and a new password (I'm guessing that's what they tried to do):
![screen shot 2018-08-08 at 1 59 23 pm](https://user-images.githubusercontent.com/1202838/43864242-046b6b18-9b14-11e8-9b45-29c8230298f1.png)
- I think clicked "forgot my password"
![screen shot 2018-08-08 at 2 00 50 pm](https://user-images.githubusercontent.com/1202838/43864240-04314abe-9b14-11e8-81a9-9e8d42cdb0a6.png)
- Got the email with the code:
![screen shot 2018-08-08 at 2 00 56 pm](https://user-images.githubusercontent.com/1202838/43864238-0407928c-9b14-11e8-8ec2-521793e1f1ee.png)
- Entered the code:
![screen shot 2018-08-08 at 2 01 15 pm](https://user-images.githubusercontent.com/1202838/43864236-03ed1074-9b14-11e8-9fd8-45eac9612248.png)
- Successful reset:
![screen shot 2018-08-08 at 2 01 37 pm](https://user-images.githubusercontent.com/1202838/43864235-03d0137a-9b14-11e8-8f63-acb4abe073d6.png)
- Error upon loggin in:
![screen shot 2018-08-08 at 2 02 06 pm](https://user-images.githubusercontent.com/1202838/43864234-03b51002-9b14-11e8-9009-cb770d1da479.png)
- Hit refresh and it took me to the first step of onboarding:
![screen shot 2018-08-08 at 2 02 30 pm](https://user-images.githubusercontent.com/1202838/43864233-039780aa-9b14-11e8-9b64-d878f2fabff2.png)
- Let me add a service location and my name then got this error:
![screen shot 2018-08-08 at 2 03 21 pm](https://user-images.githubusercontent.com/1202838/43864232-03769fde-9b14-11e8-86fe-40e81a64ae48.png)
- My AccountStatusID is still -1 in the database

### Resolving this
I think to create the best user experience, we should send an email after they sign up for the newsletter (or if someone refers another user) that is similar to Verify my email but with a different message with the call to action "Create my account" that brings them to a page that just asks for them to create a password, takes them to onboarding (listing if isProfessional checked), and at this stage the email address is automatically verified. We should also add a pop-up after they enter their email in the module that makes the next steps clear (If you'd like to create an account, please respond to the email we've just sent).

Let me know your thoughts!

**Comment by IagoSRL** [comment]
Thanks @joshdanielson for the research!  Weird user experience we have for this :-( it's really incredible some user found all that roadblocks and still continued to the last possible step!

Your proposal sounds good for me; even, if the user drop/forgot the email and attempt an standard sign-up, our fallback behavior must to be sending that email again (rather than the current 'welcome' one).

**Comment by IagoSRL** [comment]
I agree with the UX of the create-reset but almost it works. Please feel free to open an issue for it.
Would do the copy

**Comment by IagoSRL** [comment]
Done the copy., closing
