### ISSUE TITLE
Add San Joaquin Delta College to california-community-college-students landing page

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#883]
### Long Description
A new college is being onboard as part of our contract and needs to be on the drop-down menu for the landing page.

#### To-dos:
- [x] Add "517", "San Joaquin Delta College" to the drop-down
- [x] Add to the https://loconomics.com/welcome/ccc-partners drop-down, too
- [x] Run a live build for the landing pages
- [x] Test

**Comment by IagoSRL** [comment]
It's released on *live*
