### ISSUE TITLE
Remove and prevent circular dependencies

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#888]
### Research
Working at refactor #460, found circular dependencies causing problems:
- Crashes loading modules when having mixed CJS<->ESM syntax between the modules involved (both on direct dependencies and when another module is in between).
  - in detail: one of the modules getting loaded get errors because some exported members are undefined, still not initialized, at runtime.
  - was noted at [this issue 744 comment already](https://github.com/loconomics/loconomics/issues/744#issuecomment-423107797).
- Breaks fine tuning optimizations at the javascript bundles (Browserify and factor-bundle plugin)
  - in detail: increasing the threshold from default 1 to get smaller first load sizes breaks at runtime
  - found at circular dependency between data/calendar.js and data/bookings.js.
- May introduce other kind of bugs difficult to detect/debug.

### Proposal
Prevent us from having circular dependencies, using tooling we can auto detect it and add it to the CI task so doesn't let us to commit new ones, aside from researching current ones so we can fix them.

There is a tool named **madge** that count dependencies and find circular dependencies. It was set-up at #460 branch as a package script, with an alias 'find-circular-dependencies' that throws error when founds something detailing which modules are affected.

### Tasks
- [ ] Find and remove current circular dependencies
  - [ ] **Locked:** the tool 'madge' is supposed to work with CJS syntax, but on my testing this was buggy and only worked well with ESM syntax. So we should go further implementing issue #744, almost regarding the task of converting module syntax, so we can trust the findings of this tool.
- [ ] Enable the script `find-circular-dependencies` as part of the task executed by the CI so it prevents us from introducing new ones.

**Comment by IagoSRL** [comment]
At branch #460, removed the two circular dependencies detected by Madge currently (running `npm run find-circular-dependencies`): between data/calendar.js and data/bookings.js, data/weeklySchedule.js.

Now the tasks says "No circular dependency found!" and exits with success code, but is still not trustful since it doesn't covers correctly CJS syntax and we have a lot in use (maybe there is not more, but not sure).
